layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: carisa-z-b89b7b230
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Sing
    web_url: https://www.bilibili.com/video/BV1ct4y1n7t9/
    image_url: https://i.ytimg.com/vi/Xo2fExR-zrU/maxresdefault.jpg
    
  - name: Jump
    web_url: https://www.bilibili.com/video/BV1ct4y1n7t9/
    image_url: https://i.ytimg.com/vi/Xo2fExR-zrU/maxresdefault.jpg
    
  - name: Rap
    web_url: https://www.bilibili.com/video/BV1ct4y1n7t9/
    image_url: https://i.ytimg.com/vi/Xo2fExR-zrU/maxresdefault.jpg
    
  - name: Basketball
    web_url: https://www.bilibili.com/video/BV1ct4y1n7t9/
    image_url: https://i.ytimg.com/vi/Xo2fExR-zrU/maxresdefault.jpg
