layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: carisa-z-b89b7b230
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: sing
    web_url: https://geng.fandom.com/zh/wiki/%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E
    image_url: https://static.wikia.nocookie.net/geng/images/6/62/%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E.png/revision/latest?cb=20221205055948&path-prefix=zh
    
  - name: jump
    web_url: https://geng.fandom.com/zh/wiki/%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E
    image_url: https://static.wikia.nocookie.net/geng/images/6/62/%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E.png/revision/latest?cb=20221205055948&path-prefix=zh
    
  - name: rap
    web_url: https://geng.fandom.com/zh/wiki/%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E
    image_url: https://static.wikia.nocookie.net/geng/images/6/62/%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E.png/revision/latest?cb=20221205055948&path-prefix=zh
    
  - name: basketball
    web_url: https://geng.fandom.com/zh/wiki/%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E
    image_url: https://static.wikia.nocookie.net/geng/images/6/62/%E9%B8%A1%E4%BD%A0%E5%A4%AA%E7%BE%8E.png/revision/latest?cb=20221205055948&path-prefix=zh
